### ISSUE TITLE
Energy buy price is zero

### ISSUE THREAD

**Issue by HACS-bank** [jmcollin78/solar_optimizer#8]
Some power supply contracts do not pay for export energy 

It would be logical for the energy buy price to be optional in which case, if not entered in config, treat as zero.

**Comment by lostcontrol** [comment]
Hijacking yet another thread since I didn't get any answer [here](https://github.com/jmcollin78/solar_optimizer/issues/4#issuecomment-1821395163) and my question is related.

I'm pretty sure that every electricity supplier in the world is buying energy at a lower price than it is selling it. So isn't minimizing the energy import good enough? I'm trying to understand why energy price is actually required. Usually, you want to optimize your "auto-consommation" so just looking at energy should be enough to do the job, no?

**Comment by jmcollin78** [comment]
I cannot optimize a function which is always 0. This make no sense. If you don't have price put 1 or what you want in the price but not 0.
